In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [2]:
tweet = pd.read_csv(r"C:\Users\SALLA BHAVANA\Desktop\data science\naive baiyes Classifier\Datasets_Naive Bayes\Disaster_tweets_NB.csv")

In [3]:
tweet.text.describe()

count                                                  7613
unique                                                 7503
top       11-Year-Old Boy Charged With Manslaughter of T...
freq                                                     10
Name: text, dtype: object

In [12]:
tweet.columns

Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object')

In [14]:
tweet1=tweet.loc[:,['text','target']]

In [4]:
import re

In [8]:
def cleaning_text(i):
    i=re.sub("[^A-Za-z" "]+", " ",i).lower()
    w=[]
    for word in i.split():
        if len(word)>3:
            w.append(word)
    return (" ".join(w))

In [9]:
# testing above function with sample text => removes punctuations, numbers
cleaning_text("Hope you are having a good week. Just checking in")

'hope having good week just checking'

In [15]:
tweet1.text=tweet1.text.apply(cleaning_text)

In [16]:
tweet1.text

0              deeds reason this earthquake allah forgive
1                      forest fire near ronge sask canada
2       residents asked shelter place being notified o...
3       people receive wildfires evacuation orders cal...
4       just sent this photo from ruby alaska smoke fr...
                              ...                        
7608    giant cranes holding bridge collapse into near...
7609    aria ahrary thetawniest control wild fires cal...
7610                           volcano hawaii http zdtoyd
7611    police investigating after bike collided with ...
7612    latest more homes razed northern california wi...
Name: text, Length: 7613, dtype: object

In [17]:
tweet1= tweet1.loc[tweet1.text!="",:]

In [32]:
#split the data
from sklearn.model_selection import train_test_split

In [33]:
tweet_train, tweet_test = train_test_split(tweet1, test_size = 0.2)

In [34]:
def split_into_words(i):
    return [word for word in i.split(" ")]

In [35]:
# Defining the preparation of email texts into word count matrix format - Bag of Words
tweet_bow= CountVectorizer(analyzer=split_into_words).fit(tweet1.text)

In [36]:
tweet_matrix = tweet_bow.transform(tweet1.text)

In [37]:
tweet_test_matrix = tweet_bow.transform(tweet_test.text)

In [38]:
tweet_train_matrix = tweet_bow.transform(tweet_train.text)

In [39]:
# Learning Term weighting and normalizing on entire emails
tfidf_transformer = TfidfTransformer().fit(tweet_matrix)

In [40]:
test_tfidf=tfidf_transformer.transform(tweet_test_matrix)

In [41]:
train_tfidf=tfidf_transformer.transform(tweet_train_matrix)

In [42]:
test_tfidf.shape

(1522, 19279)

In [43]:
train_tfidf.shape

(6088, 19279)

In [44]:
from sklearn.naive_bayes import MultinomialNB as MB

In [45]:
classifier_mb = MB()

In [46]:
classifier_mb.fit(train_tfidf, tweet_train.target)

MultinomialNB()

In [47]:
test_pred_m = classifier_mb.predict(test_tfidf)
test_pred_m

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(test_pred_m, tweet_test.target)

0.816688567674113

In [51]:
pd.crosstab(test_pred_m, tweet_test.target)

target    0    1
row_0           
0       796  205
1        74  447

In [52]:
train_pred_m = classifier_mb.predict(train_tfidf)
train_pred_m

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(train_pred_m, tweet_train.target)

0.9034165571616294

In [54]:
pd.crosstab(train_pred_m, tweet_train.target)

target     0     1
row_0             
0       3396   515
1         73  2104

In [73]:
classifier_mb = MB(alpha=0.5)

In [74]:
classifier_mb.fit(train_tfidf, tweet_train.target)

MultinomialNB(alpha=0.5)

In [75]:
test_pred_m = classifier_mb.predict(test_tfidf)
test_pred_m

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(test_pred_m, tweet_test.target)

0.8127463863337714

In [77]:
pd.crosstab(test_pred_m, tweet_test.target)

target    0    1
row_0           
0       777  192
1        93  460

In [78]:
train_pred_m = classifier_mb.predict(train_tfidf)
train_pred_m

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [79]:
from sklearn.metrics import accuracy_score
accuracy_score(train_pred_m, tweet_train.target)

0.9262483574244416

In [80]:
pd.crosstab(train_pred_m, tweet_train.target)

target     0     1
row_0             
0       3399   379
1         70  2240